apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-backend
  namespace: {{ include "dora.namespace" . }}
  labels:
    {{- include "dora.labels" . | nindent 4 }}
  {{- if .Values.backend.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-frontend
  namespace: {{ include "dora.namespace" . }}
  labels:
    {{- include "dora.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: {{ include "dora.namespace" . }}
  labels:
    {{- include "dora.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
