"""initial schema

Revision ID: deb41848adf6
Revises: 
Create Date: 2026-05-30 17:49:00.815846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb41848adf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('prior_value', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('channels_attempted', sa.String(length=64), nullable=True),
    sa.Column('delivery_status', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_fired_at'), 'alert_events', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('operator', sa.String(length=2), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('channels', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'metric', name='uq_alert_rule_repo_metric')
    )
    op.create_index(op.f('ix_alert_rules_repo'), 'alert_rules', ['repo'], unique=False)
    op.create_table('claude_code_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_sessions', sa.Integer(), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=True),
    sa.Column('lines_removed', sa.Integer(), nullable=True),
    sa.Column('commits_created', sa.Integer(), nullable=True),
    sa.Column('prs_created', sa.Integer(), nullable=True),
    sa.Column('edit_accepted', sa.Integer(), nullable=True),
    sa.Column('edit_rejected', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.BigInteger(), nullable=True),
    sa.Column('tokens_output', sa.BigInteger(), nullable=True),
    sa.Column('estimated_cost_cents', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'session_date', name='uq_ccs_user_date')
    )
    op.create_index('ix_ccs_session_date', 'claude_code_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_claude_code_sessions_user_email'), 'claude_code_sessions', ['user_email'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('is_merge', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha')
    )
    op.create_index('ix_commit_repo_authored_at', 'commits', ['repo', 'authored_at'], unique=False)
    op.create_index(op.f('ix_commits_repo'), 'commits', ['repo'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'sha', 'environment', name='uq_deployment_sha_env')
    )
    op.create_index('ix_deploy_repo_deployed_at', 'deployments', ['repo', 'deployed_at'], unique=False)
    op.create_index('ix_deploy_status_env', 'deployments', ['status', 'environment'], unique=False)
    op.create_index(op.f('ix_deployments_repo'), 'deployments', ['repo'], unique=False)
    op.create_table('dora_level_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'metric', 'week_start', name='uq_dora_level_snapshot')
    )
    op.create_index(op.f('ix_dora_level_snapshots_repo'), 'dora_level_snapshots', ['repo'], unique=False)
    op.create_index(op.f('ix_dora_level_snapshots_week_start'), 'dora_level_snapshots', ['week_start'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('caused_by_deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_incident_source_extid')
    )
    op.create_index('ix_incident_repo_started_at', 'incidents', ['repo', 'started_at'], unique=False)
    op.create_index('ix_incident_resolved_at', 'incidents', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_incidents_repo'), 'incidents', ['repo'], unique=False)
    op.create_table('otel_cumulative_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_key', sa.String(length=512), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'session_date', 'metric_key', name='uq_otel_cum_state')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('is_revert', sa.Boolean(), nullable=True),
    sa.Column('is_hotfix', sa.Boolean(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('assisted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'number', name='uq_pr_repo_number')
    )
    op.create_index('ix_pr_repo_first_commit_at', 'pull_requests', ['repo', 'first_commit_at'], unique=False)
    op.create_index('ix_pr_repo_merged_at', 'pull_requests', ['repo', 'merged_at'], unique=False)
    op.create_index(op.f('ix_pull_requests_repo'), 'pull_requests', ['repo'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_repo'), 'review_events', ['repo'], unique=False)
    op.create_index('ix_review_repo_pr_reviewer_submitted', 'review_events', ['repo', 'pr_number', 'reviewer', 'submitted_at'], unique=False)
    op.create_index('ix_review_repo_submitted_at', 'review_events', ['repo', 'submitted_at'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'delivery_id', name='uq_webhook_source_delivery')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('conclusion', sa.String(length=20), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('head_branch', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_wfr_repo_branch_event_started', 'workflow_runs', ['repo', 'head_branch', 'event', 'started_at'], unique=False)
    op.create_index('ix_wfr_repo_started_at', 'workflow_runs', ['repo', 'started_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_repo'), 'workflow_runs', ['repo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_repo'), table_name='workflow_runs')
    op.drop_index('ix_wfr_repo_started_at', table_name='workflow_runs')
    op.drop_index('ix_wfr_repo_branch_event_started', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_review_repo_submitted_at', table_name='review_events')
    op.drop_index('ix_review_repo_pr_reviewer_submitted', table_name='review_events')
    op.drop_index(op.f('ix_review_events_repo'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_pull_requests_repo'), table_name='pull_requests')
    op.drop_index('ix_pr_repo_merged_at', table_name='pull_requests')
    op.drop_index('ix_pr_repo_first_commit_at', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_table('otel_cumulative_state')
    op.drop_index(op.f('ix_incidents_repo'), table_name='incidents')
    op.drop_index('ix_incident_resolved_at', table_name='incidents')
    op.drop_index('ix_incident_repo_started_at', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_dora_level_snapshots_week_start'), table_name='dora_level_snapshots')
    op.drop_index(op.f('ix_dora_level_snapshots_repo'), table_name='dora_level_snapshots')
    op.drop_table('dora_level_snapshots')
    op.drop_index(op.f('ix_deployments_repo'), table_name='deployments')
    op.drop_index('ix_deploy_status_env', table_name='deployments')
    op.drop_index('ix_deploy_repo_deployed_at', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_commits_repo'), table_name='commits')
    op.drop_index('ix_commit_repo_authored_at', table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_claude_code_sessions_user_email'), table_name='claude_code_sessions')
    op.drop_index('ix_ccs_session_date', table_name='claude_code_sessions')
    op.drop_table('claude_code_sessions')
    op.drop_index(op.f('ix_alert_rules_repo'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_fired_at'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
