apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-backend
  namespace: dora-metrics
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-frontend
  namespace: dora-metrics
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: dora-metrics
automountServiceAccountToken: false
